### ISSUE TITLE
Try to find a way to set default hotkeys

### ISSUE THREAD

**Issue by zachary-foster** [ropenscilabs/trackmd#2]
I am not sure if this is possible. The hotkey settings seem to be stored for each user and are preserved across sessions.

**Comment by MilesMcBain** [comment]
Could use some ideas from @yonicd here: https://github.com/yonicd/rsam

Be aware doing this automatically violates CRAN policy.

**Comment by zachary-foster** [comment]
Thanks @MilesMcBain!

> Be aware doing this automatically violates CRAN policy.

 I guess we wont do it then, but its good to know its possible!

**Comment by MilesMcBain** [comment]
No worries! To clarify 'automatically': you CAN do it, but you have to have
a dialogue that asks user permission or a self explanatory method like
`set_rstudio_keybindings()`.

**Comment by yonicd** [comment]
`rsam` does comply now with CRAN policy, I just haven't resubmitted. the [onload](https://github.com/yonicd/rsam/blob/master/R/zzz.R) functions were added to have a user confirmation step.

**Comment by zachary-foster** [comment]
Thanks @MilesMcBain and @yonicd! This will make our package much more convenient to use.

**Comment by yonicd** [comment]
You may also find remedy insightful https://github.com/thinkr-open/remedy

**Comment by zachary-foster** [comment]
Looks cool @yonicd! Thanks for the link
