### ISSUE TITLE
TO DO 

### ISSUE THREAD

**Issue by sctyner** [ropenscilabs/trackmd#4]
To Do for the remainder of #runconf18 

- [x] Function to diff 2 files and add markup (Zach) 
- [ ] When / how to refresh the HTML - is there a way to set the clock back to 0 after every key stroke? Then it won't refresh until X seconds have elapsed, then resets back to 0.  (Sam) 
- [ ] Accepting / rejecting / skipping changes 
- [x] Research with pandoc - what to do? It's all xml.  (Sam) 
- [x] Servr to render in the Viewer instead?

**Comment by zachary-foster** [comment]
All these points are either done, not applicable to our current set up, or are described in other issues, so I am closing this one.
