### ISSUE TITLE
doesn't work with custom .csl

### ISSUE THREAD

**Issue by doomlab** [ropenscilabs/trackmd#8]
I have a document with custom .csl in the `yaml` ([see here](https://github.com/doomlab/Grade-Lean/blob/master/PG%20Manuscript.Rmd)). The csl is in the folder so we can knit together the document, but the track changes does not like that:

```
> trackmd::trackChanges(paste(getwd(), "/PG Manuscript.Rmd", sep=""))
pandoc-citeproc: PandocResourceNotFound "apa6.csl"
Error running filter /Applications/RStudio.app/Contents/MacOS/pandoc/pandoc-citeproc:
Filter returned error status 1
Error: pandoc document conversion failed with error 83
```

Turning that line off temporarily also reveals it does not like the bibliography line: `bibliography      : ["grade.bib"]`. Is there a way to ignore calls to files like that?

**Comment by zachary-foster** [comment]
I am sorry, but this package is basically a prototype at this point. I have not had time to work on it lately and I am preparing for and attending an international conference the next few weeks. I might have time to look at this soon, but I can not guarantee it.
